# Generated by Django 4.2.4 on 2023-08-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_icon', models.CharField(max_length=50)),
                ('service_heading', models.CharField(max_length=100)),
                ('service_desc', models.TextField()),
            ],
        ),
    ]
