# Generated by Django 4.2.4 on 2023-09-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_aboutsection_contactus_herosection_ourpartner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='description',
            field=models.TextField(),
        ),
    ]
