# Generated by Django 4.2.4 on 2023-08-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_interiorprojects_projectcategory_projectimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interiorprojects',
            name='cover_image',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='project_image/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='project_image/'),
        ),
    ]
