# Generated by Django 4.2.4 on 2023-09-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_projectcategory_filter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('about_me', models.TextField()),
                ('about_me_more', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(default=None, max_length=250, null=True, upload_to='hero_image/')),
            ],
        ),
        migrations.CreateModel(
            name='OurPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(default=None, max_length=250, null=True, upload_to='logo_image/')),
            ],
        ),
        migrations.AddField(
            model_name='interiorservice',
            name='title',
            field=models.CharField(default='Our Services', max_length=50),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='title',
            field=models.CharField(default='Our Portfolio', max_length=50),
        ),
    ]
