# Generated by Django 4.2.4 on 2023-09-02 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_aboutsection_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='EnquiryData',
        ),
    ]
